# project informations

name: gitgram
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

# dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  equatable: ^2.0.7
  google_fonts: ^6.2.1


# system dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

